### CRUD FILM ###

GET http://localhost:3010/api/films

###

GET http://localhost:3010/api/films/661fa713118c544e0af2d63d

###
POST http://localhost:3010/api/films
content-type: application/json

{
  "title": "Example Film",
  "releaseYear": 2024,
  "genre": "Action",
  "directors": [
    {
      "name": "Director One",
      "birthdate": "1978-05-15T00:00:00.000Z",
      "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    },
    {
      "name": "Director Two",
      "birthdate": "1985-10-20T00:00:00.000Z",
      "biography": "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    }
  ]
}

###
DELETE http://localhost:3010/api/films/661f9d56ca969489782048d3


###
PUT http://localhost:3010/api/films/661f8d762357125add97ef6c
content-type: application/json

{
    "titre": "Dune 2",
    "realeaseYear": 2024,
    "genre": "Science Fiction",
    "directors": [
        {
            "nom": "Realisateur 1",
            "birthdate": "2024-04-17T12:00:00Z",
            "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
        }
    ]
}

### CRUD REALISATEUR ###

GET http://localhost:3010/api/realisateurs

###

GET http://localhost:3010/api/realisateurs/6620050727df937d6a75ba57

###

POST http://localhost:3010/api/realisateurs
content-type: application/json

{
    "nom": "Realisateur 1",
    "birthdate": "2024-04-17T12:00:00Z",
    "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
}

###

DELETE http://localhost:3010/api/realisateurs/6620050227df937d6a75ba55


###
PUT http://localhost:3010/api/realisateurs/6620050227df937d6a75ba55
content-type: application/json

{
    "nom": "Realisateur 2",
    "birthdate": "2024-04-17T12:00:00Z",
    "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
}

### CRUD SEANCE ###

GET http://localhost:3010/api/seances

###

GET http://localhost:3010/api/seances/661fa713118c544e0af2d63d

###

POST http://localhost:3010/api/seances
content-type: application/json

{
  "film": {
    "title": "Dune 1",
    "releaseYear": 2024,
    "genre": "Science Fiction",
    "directors": [
      {
        "nom": "Realisateur 1",
        "birthdate": "2024-04-17T12:00:00Z",
        "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
      },
      {
        "nom": "Realisateur 2",
        "birthdate": "2024-04-17T12:00:00Z",
        "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
      }
    ]
  },
  "date": "2024-04-17T12:00:00Z",
  "time": "12:00",
  "availableSeats": 100
}



###

DELETE http://localhost:3010/api/seances/661f9d56ca969489782048d3


###
PUT http://localhost:3010/api/seances/661f8d762357125add97ef6c
content-type: application/json

{
  "film": {
    "title": "Dune 1",
    "releaseYear": 2024,
    "genre": "Science Fiction",
    "directors": [
      {
        "nom": "Realisateur 1",
        "birthdate": "2024-04-17T12:00:00Z",
        "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
      },
      {
        "nom": "Realisateur 2",
        "birthdate": "2024-04-17T12:00:00Z",
        "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
      }
    ]
  },
  "date": "2024-04-17T12:00:00Z",
  "time": "12:00",
  "availableSeats": 100
}
